-- MySQL Script generated by MySQL Workbench
-- Sun May  5 22:42:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crowdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crowdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crowdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crowdb` ;

-- -----------------------------------------------------
-- Table `crowdb`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`day` (
  `idday` INT NOT NULL AUTO_INCREMENT,
  `day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idday`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`type_routine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`type_routine` (
  `idtype_routine` INT NOT NULL,
  `type_routine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype_routine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`routine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`routine` (
  `idroutine` INT NOT NULL AUTO_INCREMENT,
  `routine` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `idtype_routine` INT NOT NULL,
  PRIMARY KEY (`idroutine`),
  INDEX `idtype_routine_idx` (`idtype_routine` ASC) VISIBLE,
  CONSTRAINT `idtype_routine`
    FOREIGN KEY (`idtype_routine`)
    REFERENCES `crowdb`.`type_routine` (`idtype_routine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`day_routine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`day_routine` (
  `idday_routine` INT NOT NULL,
  `idroutine` INT NOT NULL,
  `idday` INT NOT NULL,
  PRIMARY KEY (`idday_routine`),
  INDEX `idday_idx` (`idday` ASC) VISIBLE,
  INDEX `idroutine_idx` (`idroutine` ASC) VISIBLE,
  CONSTRAINT `idday`
    FOREIGN KEY (`idday`)
    REFERENCES `crowdb`.`day` (`idday`),
  CONSTRAINT `idroutine`
    FOREIGN KEY (`idroutine`)
    REFERENCES `crowdb`.`routine` (`idroutine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`muscular_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`muscular_group` (
  `idmuscular_group` INT NOT NULL,
  `muscular_group` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmuscular_group`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`exercise_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`exercise_type` (
  `idtype_exercise` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype_exercise`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`exercise` (
  `idexercise` INT NOT NULL AUTO_INCREMENT,
  `exercise` VARCHAR(45) NOT NULL,
  `idtype_exercise` INT NOT NULL,
  ` idmuscular_group` INT NOT NULL,
  PRIMARY KEY (`idexercise`),
  INDEX `idtype_exercise_idx` (`idtype_exercise` ASC) VISIBLE,
  INDEX `idmuscular_group_idx` (` idmuscular_group` ASC) VISIBLE,
  CONSTRAINT `idmuscular_group`
    FOREIGN KEY (` idmuscular_group`)
    REFERENCES `crowdb`.`muscular_group` (`idmuscular_group`),
  CONSTRAINT `idtype_exercise`
    FOREIGN KEY (`idtype_exercise`)
    REFERENCES `crowdb`.`exercise_type` (`idtype_exercise`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`exercise_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`exercise_day` (
  `idexercise_day` INT NOT NULL,
  `idday` INT NOT NULL,
  `idexercise` INT NOT NULL,
  `series` VARCHAR(45) NOT NULL,
  `repetition` VARCHAR(45) NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `rest` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idexercise_day`),
  INDEX `idaday_idx` (`idday` ASC) VISIBLE,
  INDEX `idexercise_idx` (`idexercise` ASC) VISIBLE,
  CONSTRAINT `idaday`
    FOREIGN KEY (`idday`)
    REFERENCES `crowdb`.`day` (`idday`),
  CONSTRAINT `idexercise`
    FOREIGN KEY (`idexercise`)
    REFERENCES `crowdb`.`exercise` (`idexercise`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `weight` FLOAT NOT NULL,
  `age` INT NOT NULL,
  `gender` INT NOT NULL,
  `exercise_historial` VARCHAR(45) NOT NULL,
  `height` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `crowdb`.`user_routine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowdb`.`user_routine` (
  `iduser_routine` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idroutine` INT NOT NULL,
  PRIMARY KEY (`iduser_routine`),
  INDEX `idusuario_idx` (`iduser` ASC) VISIBLE,
  INDEX `idroutine_idx` (`idroutine` ASC) VISIBLE,
  CONSTRAINT `fk_user_routine_user_id` -- Nombre único para esta restricción
    FOREIGN KEY (`iduser`)
    REFERENCES `crowdb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_routine_routine_id` -- Nombre único para esta restricción
    FOREIGN KEY (`idroutine`)
    REFERENCES `crowdb`.`routine` (`idroutine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
